version: "3.5"

services:
  app:
    image: node:14-alpine
    container_name: react-app
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    user: ${CURRENT_UID}
    tty: true